services:
  vodloft:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: vodloft
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./config:/config
      - ./downloads:/downloads
    environment:
      - TZ=Europe/Amsterdam
